# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/filip/workspace/ccpp/raspiOS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/filip/workspace/ccpp/raspiOS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filip/workspace/ccpp/raspiOS/CMakeFiles /home/filip/workspace/ccpp/raspiOS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/filip/workspace/ccpp/raspiOS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RaspiOS

# Build rule for target.
RaspiOS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RaspiOS
.PHONY : RaspiOS

# fast build rule for target.
RaspiOS/fast:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/build
.PHONY : RaspiOS/fast

src/LPI.o: src/LPI.cc.o
.PHONY : src/LPI.o

# target to build an object file
src/LPI.cc.o:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/LPI.cc.o
.PHONY : src/LPI.cc.o

src/LPI.i: src/LPI.cc.i
.PHONY : src/LPI.i

# target to preprocess a source file
src/LPI.cc.i:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/LPI.cc.i
.PHONY : src/LPI.cc.i

src/LPI.s: src/LPI.cc.s
.PHONY : src/LPI.s

# target to generate assembly for a file
src/LPI.cc.s:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/LPI.cc.s
.PHONY : src/LPI.cc.s

src/input.o: src/input.cc.o
.PHONY : src/input.o

# target to build an object file
src/input.cc.o:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/input.cc.o
.PHONY : src/input.cc.o

src/input.i: src/input.cc.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.cc.i:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/input.cc.i
.PHONY : src/input.cc.i

src/input.s: src/input.cc.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.cc.s:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/input.cc.s
.PHONY : src/input.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/pios.o: src/pios.cc.o
.PHONY : src/pios.o

# target to build an object file
src/pios.cc.o:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/pios.cc.o
.PHONY : src/pios.cc.o

src/pios.i: src/pios.cc.i
.PHONY : src/pios.i

# target to preprocess a source file
src/pios.cc.i:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/pios.cc.i
.PHONY : src/pios.cc.i

src/pios.s: src/pios.cc.s
.PHONY : src/pios.s

# target to generate assembly for a file
src/pios.cc.s:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/pios.cc.s
.PHONY : src/pios.cc.s

src/profiling.o: src/profiling.cc.o
.PHONY : src/profiling.o

# target to build an object file
src/profiling.cc.o:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/profiling.cc.o
.PHONY : src/profiling.cc.o

src/profiling.i: src/profiling.cc.i
.PHONY : src/profiling.i

# target to preprocess a source file
src/profiling.cc.i:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/profiling.cc.i
.PHONY : src/profiling.cc.i

src/profiling.s: src/profiling.cc.s
.PHONY : src/profiling.s

# target to generate assembly for a file
src/profiling.cc.s:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/profiling.cc.s
.PHONY : src/profiling.cc.s

src/ui.o: src/ui.cc.o
.PHONY : src/ui.o

# target to build an object file
src/ui.cc.o:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/ui.cc.o
.PHONY : src/ui.cc.o

src/ui.i: src/ui.cc.i
.PHONY : src/ui.i

# target to preprocess a source file
src/ui.cc.i:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/ui.cc.i
.PHONY : src/ui.cc.i

src/ui.s: src/ui.cc.s
.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.cc.s:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/ui.cc.s
.PHONY : src/ui.cc.s

src/window.o: src/window.cc.o
.PHONY : src/window.o

# target to build an object file
src/window.cc.o:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/window.cc.o
.PHONY : src/window.cc.o

src/window.i: src/window.cc.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cc.i:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/window.cc.i
.PHONY : src/window.cc.i

src/window.s: src/window.cc.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cc.s:
	$(MAKE) -f CMakeFiles/RaspiOS.dir/build.make CMakeFiles/RaspiOS.dir/src/window.cc.s
.PHONY : src/window.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... RaspiOS"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/LPI.o"
	@echo "... src/LPI.i"
	@echo "... src/LPI.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pios.o"
	@echo "... src/pios.i"
	@echo "... src/pios.s"
	@echo "... src/profiling.o"
	@echo "... src/profiling.i"
	@echo "... src/profiling.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

